language: php

env:
    global:
        - XDEBUG_MODE=coverage

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.3
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
